-- Seed: 74 productos del catálogo real de Smile
-- Precios = NULL (placeholder — el cliente debe completarlos)

INSERT INTO productos (nombre, slug, categoria, formato, formato_detalle, stock, precio_minorista, precio_mayorista, destacado) VALUES
('Ají Fresco', 'aji-fresco-caja', 'verduras', 'caja', NULL, 1, NULL, NULL, false),
('Ají Oro', 'aji-oro-kilo', 'verduras', 'kilo', NULL, 18, NULL, NULL, false),
('Ajinomoto', 'ajinomoto-kilo', 'abarrotes', 'kilo', NULL, 3, NULL, NULL, false),
('Ajo', 'ajo-unidad', 'verduras', 'unidad', NULL, 3, NULL, NULL, false),
('Ajo', 'ajo-kilo', 'verduras', 'kilo', NULL, 2, NULL, NULL, false),
('Apio', 'apio-unidad', 'verduras', 'unidad', NULL, 1, NULL, NULL, false),
('Arveja Partida', 'arveja-partida-kilo', 'legumbres_granos', 'kilo', NULL, 2, NULL, NULL, false),
('Betarraga', 'betarraga-5-unidades', 'verduras', 'paquete', '5 unidades', 5, NULL, NULL, false),
('Brócoli', 'brocoli-unidad', 'verduras', 'unidad', NULL, 213, NULL, NULL, true),
('Cebolla Grande', 'cebolla-grande-unidad', 'verduras', 'unidad', NULL, 10, NULL, NULL, false),
('Cebolla Mediana', 'cebolla-mediana-kilo', 'verduras', 'kilo', NULL, 5, NULL, NULL, false),
('Cebolla Morada', 'cebolla-morada-kilo', 'verduras', 'kilo', NULL, 5, NULL, NULL, false),
('Cebolla Morada Perla Grande', 'cebolla-morada-perla-grande-malla', 'verduras', 'malla', NULL, 1, NULL, NULL, false),
('Cebolla Vieja', 'cebolla-vieja-saco', 'verduras', 'saco', NULL, 5, NULL, NULL, false),
('Cebollín Primera', 'cebollin-primera-docena', 'hierbas', 'docena', NULL, 55, NULL, NULL, true),
('Champiñón Mediano', 'champinon-mediano-kilo', 'verduras', 'kilo', NULL, 6, NULL, NULL, false),
('Ciboulette', 'ciboulette-grande', 'hierbas', 'paquete', 'grande', 2, NULL, NULL, false),
('Ciboulette', 'ciboulette-pequeno', 'hierbas', 'paquete', 'pequeño', 4, NULL, NULL, false),
('Cilantro', 'cilantro-pequeno', 'hierbas', 'paquete', 'pequeño', 2, NULL, NULL, false),
('Cilantro', 'cilantro-grande', 'hierbas', 'paquete', 'grande', 6, NULL, NULL, false),
('Col China', 'col-china-6-unidades', 'verduras', 'caja', '6 unidades', 2, NULL, NULL, false),
('Coliflor', 'coliflor-unidad', 'verduras', 'unidad', NULL, 114, NULL, NULL, true),
('Cuscús', 'cuscus-500-gramos', 'abarrotes', 'bolsa', '500 gramos', 1, NULL, NULL, false),
('Diente de Dragón', 'diente-de-dragon-kilo', 'frutas', 'kilo', NULL, 1, NULL, NULL, false),
('Espinaca', 'espinaca-kilo', 'verduras', 'kilo', NULL, 7, NULL, NULL, false),
('Frutilla', 'frutilla-caja', 'frutas', 'caja', NULL, 1, NULL, NULL, false),
('Garbanzo', 'garbanzo-kilo', 'legumbres_granos', 'kilo', NULL, 2, NULL, NULL, false),
('Huevos Extra Blanco', 'huevos-extra-blanco-30-unidades', 'huevos', 'bandeja', '30 unidades', 2, NULL, NULL, false),
('Huevos Extra Blanco', 'huevos-extra-blanco-caja', 'huevos', 'caja', NULL, 1, NULL, NULL, false),
('Jengibre', 'jengibre-kilo', 'verduras', 'kilo', NULL, 2, NULL, NULL, false),
('Kiwi', 'kiwi-kilo', 'frutas', 'kilo', NULL, 2, NULL, NULL, false),
('Lechuga Costina', 'lechuga-costina-caja', 'verduras', 'caja', NULL, 1, NULL, NULL, false),
('Lechuga Costina', 'lechuga-costina-unidad', 'verduras', 'unidad', NULL, 4, NULL, NULL, false),
('Lechuga Escarola', 'lechuga-escarola-unidad', 'verduras', 'unidad', NULL, 1, NULL, NULL, false),
('Lenteja', 'lenteja-kilo', 'legumbres_granos', 'kilo', NULL, 2, NULL, NULL, false),
('Limón Amarillo', 'limon-amarillo-malla', 'frutas', 'malla', NULL, 2, NULL, NULL, false),
('Limón Sutil', 'limon-sutil-caja', 'frutas', 'caja', NULL, 1, NULL, NULL, false),
('Limón Sutil', 'limon-sutil-kilo', 'frutas', 'kilo', NULL, 2, NULL, NULL, false),
('Limón Mediano', 'limon-mediano-malla', 'frutas', 'malla', NULL, 2, NULL, NULL, false),
('Mango', 'mango-unidad', 'frutas', 'unidad', NULL, 1, NULL, NULL, false),
('Mango Brasilero Maduro', 'mango-brasilero-maduro-caja', 'frutas', 'caja', NULL, 10, NULL, NULL, false),
('Manzana Fuji', 'manzana-fuji-kilo', 'frutas', 'kilo', NULL, 7, NULL, NULL, false),
('Mote', 'mote-kilo', 'abarrotes', 'kilo', NULL, 3, NULL, NULL, false),
('Naranja', 'naranja-malla', 'frutas', 'malla', NULL, 1, NULL, NULL, false),
('Pak Choi', 'pak-choi-400-gramos', 'verduras', 'bolsa', '400 gramos', 2, NULL, NULL, false),
('Palta Hass Chilena', 'palta-hass-chilena-kilo', 'frutas', 'kilo', NULL, 3.5, NULL, NULL, true),
('Papa Lavada Mediana', 'papa-lavada-mediana-saco', 'verduras', 'saco', NULL, 1, NULL, NULL, false),
('Papa Mediana', 'papa-mediana-kilo', 'verduras', 'kilo', NULL, 24, NULL, NULL, true),
('Pepino Ensalada', 'pepino-ensalada-unidad', 'verduras', 'unidad', NULL, 4, NULL, NULL, false),
('Pera', 'pera-kilo', 'frutas', 'kilo', NULL, 2, NULL, NULL, false),
('Perejil', 'perejil-grande', 'hierbas', 'paquete', 'grande', 7, NULL, NULL, false),
('Pimentón Rojo', 'pimenton-rojo-unidad', 'verduras', 'unidad', NULL, 17, NULL, NULL, false),
('Pimentón Verde', 'pimenton-verde-unidad', 'verduras', 'unidad', NULL, 23, NULL, NULL, false),
('Pimentón Rojo 3*', 'pimenton-rojo-3-caja', 'verduras', 'caja', NULL, 1, NULL, NULL, false),
('Piña Madura', 'pina-madura-unidad', 'frutas', 'unidad', NULL, 5, NULL, NULL, false),
('Piña Pre-Madura Dulce', 'pina-pre-madura-dulce-10-unidades', 'frutas', 'caja', '10 unidades', 1, NULL, NULL, false),
('Plátano', 'platano-unidad', 'frutas', 'unidad', NULL, 25, NULL, NULL, true),
('Plátano', 'platano-kilo', 'frutas', 'kilo', NULL, 1, NULL, NULL, false),
('Poroto Burro', 'poroto-burro-kilo', 'legumbres_granos', 'kilo', NULL, 2, NULL, NULL, false),
('Poroto Verde', 'poroto-verde-kilo', 'verduras', 'kilo', NULL, 3, NULL, NULL, false),
('Repollo Crespo', 'repollo-crespo-unidad', 'verduras', 'unidad', NULL, 131, NULL, NULL, true),
('Repollo Liso', 'repollo-liso-unidad', 'verduras', 'unidad', NULL, 7, NULL, NULL, false),
('Repollo Morado', 'repollo-morado-unidad', 'verduras', 'unidad', NULL, 1, NULL, NULL, false),
('Salsa de Ostras', 'salsa-de-ostras-500-gramos', 'abarrotes', 'bolsa', '500 gramos', 1, NULL, NULL, false),
('Tomate', 'tomate-kilo', 'verduras', 'kilo', NULL, 12, NULL, NULL, false),
('Tomate', 'tomate-caja', 'verduras', 'caja', NULL, 1, NULL, NULL, false),
('Tomate Cherry', 'tomate-cherry-kilo', 'verduras', 'kilo', NULL, 1, NULL, NULL, false),
('Uva Sin Pepa', 'uva-sin-pepa-kilo', 'frutas', 'kilo', NULL, 3, NULL, NULL, false),
('Zanahoria Grande', 'zanahoria-grande-kilo', 'verduras', 'kilo', NULL, 55, NULL, NULL, true),
('Zanahoria Grande', 'zanahoria-grande-saco', 'verduras', 'saco', NULL, 3, NULL, NULL, false),
('Zanahoria Mediana', 'zanahoria-mediana-kilo', 'verduras', 'kilo', NULL, 6, NULL, NULL, false),
('Zapallo Camote', 'zapallo-camote-1-kilo', 'verduras', 'trozo', '1 kilo', 2, NULL, NULL, false),
('Zapallo Italiano', 'zapallo-italiano-unidad', 'verduras', 'unidad', NULL, 31, NULL, NULL, true),
('Zapallo Italiano 1*', 'zapallo-italiano-1-caja', 'verduras', 'caja', NULL, 1, NULL, NULL, false);
